### list all msgs
GET http://localhost:3000/messages

### Create new msg
POST http://localhost:3000/messages
content-type: application/json

{
    "content": 123
}

### Get a particular msg
GET http://localhost:3000/messages/1234